defaultSemverRangePrefix: ""

enableScripts: false

initLicense: 0BSD

packageExtensions:
  "@vue/cli-service@*":
    dependencies:
      "@vue/cli-plugin-babel": "*"
      "@vue/cli-plugin-eslint": "*"
      sass: "*"
      vue-cli-plugin-files: "workspace:*"
  "@vue/cli-shared-utils@*":
    dependencies:
      vue-cli-plugin-files: "*"
  promise-inflight@*:
    dependencies:
      bluebird: "*"
  vue-eslint-parser@*:
    dependencies:
      babel-eslint: "*"
  vue-template-compiler@*:
    dependencies:
      vue: "*"

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.0.0-rc.33.js
