defaultSemverRangePrefix: ""

enableScripts: false

initLicense: 0BSD

packageExtensions:
  "@vue/cli-shared-utils@*":
    dependencies:
      vue-cli-plugin-files: "*"
  vue-eslint-parser@*:
    dependencies:
      babel-eslint: "*"
  vue-template-compiler@*:
    dependencies:
      vue: "*"
  "@vue/cli-service@*":
    dependencies:
      "@vue/cli-plugin-babel": "*"
      "@vue/cli-plugin-eslint": "*"
      "vue-cli-plugin-files": "workspace:*"
      "sass": "*"
  "promise-inflight@*":
    dependencies:
      "bluebird": "*"

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.0.0-rc.32.js
